# Generated by Django 4.0.8 on 2023-01-07 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balance', '0001_initial'),
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybalance',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='annualbalance',
            name='coin_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coin.cointype', verbose_name='coin type'),
        ),
        migrations.AddField(
            model_name='annualbalance',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
