version: '2.1'

services:

  db:
    image: postgres:15.1
    env_file:
      - ./postgres_db.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      balance_home_app_net:
        ipv4_address: 192.168.92.20

  pgadmin:
    image: dpage/pgadmin4:6.20
    env_file:
      - ./pgadmin.env
    ports:
      - "36050:80"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      balance_home_app_net:
        ipv4_address: 192.168.92.25

networks:
  balance_home_app_net:
    name: balance_home_app_net
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"