version: '2.1'

services:

  backend:
    build: djangorest
    env_file:
      - ./backend_app.env
    links:
      - db:db
      - redis:redis
    volumes:
      - ./djangorest/media:/app/media
      - ./djangorest/static:/app/static
      - ./logs/backend:/var/log/balance_app
    expose:
      - 8000
    depends_on:
      - redis
      - db
    restart: unless-stopped
    networks:
      balance_home_app_net:
        ipv4_address: 192.168.92.45

  celery:
    build: djangorest
    env_file:
      - ./backend_app.env
    links:
      - db:db
      - redis:redis
    volumes:
      - ./djangorest/media:/app/media
      - ./djangorest/static:/app/static
      - ./logs/celery:/var/log/balance_app
    depends_on:
      - redis
      - db
    restart: unless-stopped
    entrypoint: /app/celery_entrypoint.sh
    networks:
      balance_home_app_net:
        ipv4_address: 192.168.92.40

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      balance_home_app_net:
        ipv4_address: 192.168.92.30

  db:
    image: postgres:15.0
    env_file:
      - ./postgres_db.env
    expose:
      - "5432"
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      balance_home_app_net:
        ipv4_address: 192.168.92.20

  nginx:
    build: nginx
    ports: 
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./djangorest/static:/app/static
      - ./djangorest/media:/app/media
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - backend
    env_file:
      - ./nginx.env
    restart: unless-stopped
    networks:
      balance_home_app_net:
        ipv4_address: 192.168.92.10

networks:
  balance_home_app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"