# Generated by Django 4.0 on 2022-09-21 16:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_quantity', models.FloatField()),
                ('net_quantity', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)])),
            ],
            options={
                'verbose_name': 'Annual Balance',
                'verbose_name_plural': 'Annual Balances',
            },
        ),
        migrations.CreateModel(
            name='CoinType',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'CoinType',
                'verbose_name_plural': 'CoinTypes',
            },
        ),
        migrations.CreateModel(
            name='MonthlyBalance',
            fields=[
                ('annualbalance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='balance.annualbalance')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
            ],
            options={
                'verbose_name': 'Monthly Balance',
                'verbose_name_plural': 'Monthly Balances',
            },
            bases=('balance.annualbalance',),
        ),
        migrations.AddField(
            model_name='annualbalance',
            name='coin_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='balance.cointype'),
        ),
    ]
