# Generated by Django 4.0 on 2022-09-10 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_annualbalance_monthlybalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualbalance',
            old_name='quantity',
            new_name='gross_quantity',
        ),
        migrations.AddField(
            model_name='annualbalance',
            name='net_quantity',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
