version: '2.1'

services:

  backend:
    build:
      context: djangorest
      dockerfile: OnPremise.Dockerfile
    env_file:
      - ./backend_app.env
    links:
      - redis:redis
    volumes:
      - ./djangorest/src/media:/app/media
      - ./djangorest/src/static:/app/static
      - ./logs/backend:/var/log/balance_app
    expose:
      - 8000
    depends_on:
      - redis
      - celery_worker
      - celery_beat
    restart: unless-stopped
    networks:
      - balance_home_app_net_external

  celery_worker:
    build:
      context: djangorest
      dockerfile: OnPremise.Dockerfile
    env_file:
      - ./backend_app.env
    links:
      - redis:redis
    volumes:
      - ./djangorest/src/media:/app/media
      - ./djangorest/src/static:/app/static
      - ./logs/celery_worker:/var/log/balance_app
    depends_on:
      - redis
    restart: unless-stopped
    entrypoint: /app/celery_worker_entrypoint.sh
    networks:
      - balance_home_app_net_external
      
  celery_beat:
    build:
      context: djangorest
      dockerfile: OnPremise.Dockerfile
    env_file:
      - ./backend_app.env
    links:
      - redis:redis
    volumes:
      - ./djangorest/src/media:/app/media
      - ./djangorest/src/static:/app/static
      - ./logs/celery_beat:/var/log/balance_app
    depends_on:
      - redis
    restart: unless-stopped
    entrypoint: /app/celery_beat_entrypoint.sh
    networks:
      - balance_home_app_net_external

  redis:
    image: redis:7.0.7
    restart: unless-stopped
    networks:
      - balance_home_app_net_external

  nginx:
    build: nginx
    ports:
      - "8000:80"
      - "8001:443"
    volumes:
      - ./djangorest/src/media:/app/media
      - ./djangorest/src/static:/app/static
      - ./logs/nginx:/var/log/nginx
      - ./certs:/etc/nginx/ssl:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - balance_home_app_net_external

networks:
  balance_home_app_net_external:
    name: balance_home_app_net
    external: true