version: '3'

services:

  api:
    image: fabbo/balhom-backend-djangorest:latest
    env_file:
      - ./backend_app.env
    links:
      - redis:redis
    volumes:
      - ./logs/api:/var/log/api
      - ./certs:/certs:ro
    ports:
      - "8001:443"
    depends_on:
      - redis
      - celery_worker
      - celery_beat
    restart: unless-stopped
    networks:
      - balhom_backend_net

  celery_worker:
    image: fabbo/balhom-backend-djangorest:latest
    env_file:
      - ./backend_app.env
    links:
      - redis:redis
    volumes:
      - ./logs/celery_worker:/var/log/balance_app
    depends_on:
      - redis
    restart: unless-stopped
    entrypoint: /app/celery_worker_entrypoint.sh
    networks:
      - balhom_backend_net
      
  celery_beat:
    image: fabbo/balhom-backend-djangorest:latest
    env_file:
      - ./backend_app.env
    links:
      - redis:redis
    volumes:
      - ./logs/celery_beat:/var/log/balance_app
    depends_on:
      - redis
    restart: unless-stopped
    entrypoint: /app/celery_beat_entrypoint.sh
    networks:
      - balhom_backend_net

  redis:
    image: redis:7.0.7
    restart: unless-stopped
    networks:
      - balhom_backend_net

networks:
  balhom_backend_net:
    name: balhom_backend_net
    ipam:
      driver: default
      config:
        - subnet: "192.168.93.0/24"