@startuml architecture

component User

User --> Urls
User <-- Urls
User --> ApiUrls
User <-- ApiUrls

node Urls {
}


node ViewPermission {
}

Urls --> Views
Urls <-- Views
ViewPermission --> Views

node Views {
}

node ApiUrls {
}

ApiUrls --> ApiViews
ApiUrls <-- ApiViews
ViewPermission --> ApiViews

node ApiViews {
}

Serializers --> ApiViews
Serializers <-- ApiViews
Serializers <-- Models

node Serializers {
}

ApiFilters <-- Models
node ApiFilters {
}

Views --> Models
Views <-- Models
ApiViews --> Models
ApiViews <-- Models
ViewPermission <-- Models
node Models {
}

ApiViews --> Scheduler
node Scheduler {
}

ApiViews --> Tasks
Models <-- Tasks
Models --> Tasks
node Tasks {
}

@enduml