# Generated by Django 4.0.8 on 2022-12-30 15:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='name')),
                ('image', models.ImageField(default='core/default_image.jpg', upload_to='expense', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Expense type',
                'verbose_name_plural': 'Expense types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('description', models.CharField(blank=True, default='', max_length=2000, verbose_name='description')),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='quantity')),
                ('date', models.DateField(verbose_name='date')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('coin_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coin.cointype', verbose_name='coin type')),
                ('exp_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='expense.expensetype', verbose_name='expense type')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
    ]
