# Generated by Django 4.0 on 2022-09-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_user_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='annual_balance',
            new_name='expected_annual_balance',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='monthly_balance',
            new_name='expected_monthly_balance',
        ),
        migrations.AddField(
            model_name='user',
            name='last_annual_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_monthly_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_email_balance',
            field=models.BooleanField(default=True),
        ),
    ]
