# Generated by Django 4.0 on 2022-09-19 17:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('balance', '0001_initial'),
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueType',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='core/default_image.jpg', upload_to='revenue')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(default='', max_length=2000)),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('coin_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='balance.cointype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.user')),
                ('rev_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='revenue.revenuetype')),
            ],
            options={
                'verbose_name': 'Revenue',
                'verbose_name_plural': 'Revenues',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
    ]
