version: '3'

services:

  minio:
    image: minio/minio:RELEASE.2023-05-04T21-44-30Z
    ports:
      - "33090:33090"
      #- "33091:33091" # Uncomment for HTTPS
    env_file:
      - ./minio.env
    volumes:
      - ./minio:/data
      #- ./certs/fullchain.pem:/etc/minio/certs/public.crt # Uncomment to enabe HTTPS
      #- ./certs/privkey.pem:/etc/minio/certs/private.key # Uncomment to enabe HTTPS
    command: server -C "/etc/minio" --address ":33090" --console-address ":33091" /data
    restart: unless-stopped
    networks:
      - balhom_minio_net

networks:
  balhom_minio_net:
    name: balhom_minio_net
    ipam:
      driver: default
      config:
        - subnet: "192.168.95.0/24"