version: '3'

services:

  minio:
    image: bitnami/minio:2023.7.7
    container_name: balhom-minio
    ports:
      - "33090:9000"
      - "33091:9001"
    env_file:
      - ./minio.env
    volumes:
      - ./data:/data
      #- ./certs/fullchain.pem:/etc/minio/certs/public.crt # Uncomment to enabe HTTPS
      #- ./certs/privkey.pem:/etc/minio/certs/private.key # Uncomment to enabe HTTPS
    restart: unless-stopped
    networks:
      - balhom_minio_net

networks:
  balhom_minio_net:
    name: balhom_minio_net
    ipam:
      driver: default
      config:
        - subnet: "192.168.95.0/24"