version: '2.1'

services:

  certbot:
    build: certbot
    env_file:
      - ./certbot.env
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./acme_challenge:/var/www/certbot
      - ./log:/var/log/letsencrypt

  nginx:
    image: nginx:1.23.3
    ports:
      - "8000:80"
      - "8001:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/local.conf
      - ./acme_challenge:/var/www/certbot
    restart: unless-stopped

