# Generated by Django 4.1.7 on 2023-06-05 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code_sent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_code_sent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_coin_change',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pass_reset',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pref_coin_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verified',
        ),
        migrations.AddField(
            model_name='user',
            name='date_currency_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of last preferred currency type change'),
        ),
        migrations.AddField(
            model_name='user',
            name='pref_currency_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coin.cointype', verbose_name='preferred currency type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='count_pass_reset',
            field=models.IntegerField(default=0, verbose_name='number of requests for password reset'),
        ),
    ]
