name: Flutter App Build and Test

on:
  push:
    branches:
      - develop

jobs:
  build-test-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get
        working-directory: ./frontend-flutter/flutter
        
      - name: Generate temporary files
        run: |
          flutter pub run build_runner build --delete-conflicting-outputs
        working-directory: ./frontend-flutter/flutter

      - name: Run tests
        run: |
          flutter test
        working-directory: ./frontend-flutter/flutter

      - name: Build apk
        run: |
          flutter build apk
        working-directory: ./frontend-flutter/flutter

      - name: Build web
        run: |
          flutter build web
        working-directory: ./frontend-flutter/flutter
        
      - name: Check build Docker Image
        run: |
          export APP_VERSION=$(grep -m 1 "version =" src/pyproject.toml | tr -d '=' | cut -d' ' -f3 | tr -d '"' | tr -d '\n' | tr -d '\r')
          echo "Using version ${APP_VERSION}"
          IMAGE_TAG="${DJANGOREST_DOCKER_REPO_NAME}:${APP_VERSION}"
          docker build . -t ${IMAGE_TAG}
        env:
          DJANGOREST_DOCKER_REPO_NAME: ${{ secrets.DJANGOREST_DOCKER_REPO_NAME }}
        working-directory: ./backend-djangorest/api